//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.06 at 05:35:57 PM CET 
//


package it.incalza.myhome.input.controller.configuration;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actionComand.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="actionComand">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ON"/>
 *     &lt;enumeration value="OFF"/>
 *     &lt;enumeration value="NORTH_WEST"/>
 *     &lt;enumeration value="NORTH_EAST"/>
 *     &lt;enumeration value="NORTH"/>
 *     &lt;enumeration value="SOUTH_WEST"/>
 *     &lt;enumeration value="SOUTH_EAST"/>
 *     &lt;enumeration value="SOUTH"/>
 *     &lt;enumeration value="EAST"/>
 *     &lt;enumeration value="WEST"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "actionComand")
@XmlEnum
public enum ActionComand {

    ON,
    OFF,
    NORTH_WEST,
    NORTH_EAST,
    NORTH,
    SOUTH_WEST,
    SOUTH_EAST,
    SOUTH,
    EAST,
    WEST;

    public String value() {
        return name();
    }

    public static ActionComand fromValue(String v) {
        return valueOf(v);
    }

}
