//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.17 at 07:43:24 PM CET 
//


package it.incalza.bt.openwebnet.client.configuration;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actionComand.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="actionComand">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="STARTUP"/>
 *     &lt;enumeration value="CLOSED"/>
 *     &lt;enumeration value="PAUSE"/>
 *     &lt;enumeration value="ACTION"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "actionComand")
@XmlEnum
public enum ActionComand {

    STARTUP,
    CLOSED,
    PAUSE,
    ACTION;

    public String value() {
        return name();
    }

    public static ActionComand fromValue(String v) {
        return valueOf(v);
    }

}
