//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.06 at 05:30:39 PM CEST 
//


package it.incalza.myhome.input.controller.configuration;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.incalza.myhome.input.controller.configuration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CommandOpenWebNetComands_QNAME = new QName("http://www.incalza.it/myhome/input/controller/configuration", "OpenWebNetComands");
    private final static QName _CommandSpecialComand_QNAME = new QName("http://www.incalza.it/myhome/input/controller/configuration", "SpecialComand");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.incalza.myhome.input.controller.configuration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Command }
     * 
     */
    public Command createCommand() {
        return new Command();
    }

    /**
     * Create an instance of {@link ConfigurationCommands }
     * 
     */
    public ConfigurationCommands createConfigurationCommands() {
        return new ConfigurationCommands();
    }

    /**
     * Create an instance of {@link Commands }
     * 
     */
    public Commands createCommands() {
        return new Commands();
    }

    /**
     * Create an instance of {@link Command.OpenWebNetComands }
     * 
     */
    public Command.OpenWebNetComands createCommandOpenWebNetComands() {
        return new Command.OpenWebNetComands();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Command.OpenWebNetComands }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.incalza.it/myhome/input/controller/configuration", name = "OpenWebNetComands", scope = Command.class)
    public JAXBElement<Command.OpenWebNetComands> createCommandOpenWebNetComands(Command.OpenWebNetComands value) {
        return new JAXBElement<Command.OpenWebNetComands>(_CommandOpenWebNetComands_QNAME, Command.OpenWebNetComands.class, Command.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecialComand }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.incalza.it/myhome/input/controller/configuration", name = "SpecialComand", scope = Command.class)
    public JAXBElement<SpecialComand> createCommandSpecialComand(SpecialComand value) {
        return new JAXBElement<SpecialComand>(_CommandSpecialComand_QNAME, SpecialComand.class, Command.class, value);
    }

}
