//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.08 at 12:38:42 AM CET 
//


package it.incalza.bt.openwebnet.client.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for command complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="command">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ControllerInput" type="{http://www.incalza.it/bt/openwebnet/client/configuration}controllerInput"/>
 *         &lt;element name="OpenWebNetComand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "command", propOrder = {
    "controllerInput",
    "openWebNetComand"
})
public class Command {

    @XmlElement(name = "ControllerInput", required = true)
    protected ControllerInput controllerInput;
    @XmlElement(name = "OpenWebNetComand", required = true)
    protected String openWebNetComand;

    /**
     * Gets the value of the controllerInput property.
     * 
     * @return
     *     possible object is
     *     {@link ControllerInput }
     *     
     */
    public ControllerInput getControllerInput() {
        return controllerInput;
    }

    /**
     * Sets the value of the controllerInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControllerInput }
     *     
     */
    public void setControllerInput(ControllerInput value) {
        this.controllerInput = value;
    }

    /**
     * Gets the value of the openWebNetComand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenWebNetComand() {
        return openWebNetComand;
    }

    /**
     * Sets the value of the openWebNetComand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenWebNetComand(String value) {
        this.openWebNetComand = value;
    }

}
