//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.08 at 12:38:42 AM CET 
//


package it.incalza.bt.openwebnet.client.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for configuration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="configuration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ControllerSelected" type="{http://www.incalza.it/bt/openwebnet/client/configuration}controllerSelected"/>
 *         &lt;element name="Commands" type="{http://www.incalza.it/bt/openwebnet/client/configuration}commands"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "configuration", propOrder = {
    "controllerSelected",
    "commands"
})
public class Configuration {

    @XmlElement(name = "ControllerSelected", required = true)
    protected ControllerSelected controllerSelected;
    @XmlElement(name = "Commands", required = true)
    protected Commands commands;

    /**
     * Gets the value of the controllerSelected property.
     * 
     * @return
     *     possible object is
     *     {@link ControllerSelected }
     *     
     */
    public ControllerSelected getControllerSelected() {
        return controllerSelected;
    }

    /**
     * Sets the value of the controllerSelected property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControllerSelected }
     *     
     */
    public void setControllerSelected(ControllerSelected value) {
        this.controllerSelected = value;
    }

    /**
     * Gets the value of the commands property.
     * 
     * @return
     *     possible object is
     *     {@link Commands }
     *     
     */
    public Commands getCommands() {
        return commands;
    }

    /**
     * Sets the value of the commands property.
     * 
     * @param value
     *     allowed object is
     *     {@link Commands }
     *     
     */
    public void setCommands(Commands value) {
        this.commands = value;
    }

}
