//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.08 at 12:34:04 AM CET 
//


package it.incalza.bt.openwebnet.client.configuration;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.incalza.bt.openwebnet.client.configuration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConfigurationCommands_QNAME = new QName("http://www.incalza.it/bt/openwebnet/client/configuration", "ConfigurationCommands");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.incalza.bt.openwebnet.client.configuration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link ControllerSelected }
     * 
     */
    public ControllerSelected createControllerSelected() {
        return new ControllerSelected();
    }

    /**
     * Create an instance of {@link Commands }
     * 
     */
    public Commands createCommands() {
        return new Commands();
    }

    /**
     * Create an instance of {@link Command }
     * 
     */
    public Command createCommand() {
        return new Command();
    }

    /**
     * Create an instance of {@link ControllerInput }
     * 
     */
    public ControllerInput createControllerInput() {
        return new ControllerInput();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Configuration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.incalza.it/bt/openwebnet/client/configuration", name = "ConfigurationCommands")
    public JAXBElement<Configuration> createConfigurationCommands(Configuration value) {
        return new JAXBElement<Configuration>(_ConfigurationCommands_QNAME, Configuration.class, null, value);
    }

}
