//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.12 at 12:41:37 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.incalza.it/bt/openwebnet/client/configuration", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.incalza.bt.openwebnet.client.configuration;
